name: No root-relative links

author: 18F

description: |
  Scans a collection of source files (HTML and Markdown) to verify that there
  are no root-relative links.

inputs:
  path:
    description: |
      Path to the directory containing your source files. This directory will be
      scanned recursively.
    required: false
    default: "."
  message:
    description: |
      The message to include in annotations for links that are root-relative.
    required: false
    default: "This internal link is root-relative and should be prefixed."

runs:
  using: 'composite'
  steps:
    - run: ${GITHUB_ACTION_PATH}/check-links.sh "${{ inputs.path }}" "${{ inputs.message }}"
      shell: bash

branding:
  icon: link
  color: gray-dark